// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "git.garena.com/sea-labs-id/bootcamp/batch-02/ziad-rahmatullah/assignment-go-rest-api/dto"
	mock "github.com/stretchr/testify/mock"

	model "git.garena.com/sea-labs-id/bootcamp/batch-02/ziad-rahmatullah/assignment-go-rest-api/model"
)

// AttemptRepository is an autogenerated mock type for the AttemptRepository type
type AttemptRepository struct {
	mock.Mock
}

// FindAttempt provides a mock function with given fields: _a0, _a1
func (_m *AttemptRepository) FindAttempt(_a0 context.Context, _a1 model.Wallet) (*dto.AttemptRes, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *dto.AttemptRes
	if rf, ok := ret.Get(0).(func(context.Context, model.Wallet) *dto.AttemptRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AttemptRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Wallet) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAttempt provides a mock function with given fields: _a0, _a1
func (_m *AttemptRepository) NewAttempt(_a0 context.Context, _a1 uint) (*model.Attempt, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.Attempt
	if rf, ok := ret.Get(0).(func(context.Context, uint) *model.Attempt); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Attempt)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAttemptRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAttemptRepository creates a new instance of AttemptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAttemptRepository(t mockConstructorTestingTNewAttemptRepository) *AttemptRepository {
	mock := &AttemptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
