// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "git.garena.com/sea-labs-id/bootcamp/batch-02/ziad-rahmatullah/assignment-go-rest-api/dto"
	mock "github.com/stretchr/testify/mock"

	model "git.garena.com/sea-labs-id/bootcamp/batch-02/ziad-rahmatullah/assignment-go-rest-api/model"
)

// ResetPassTokenRepository is an autogenerated mock type for the ResetPassTokenRepository type
type ResetPassTokenRepository struct {
	mock.Mock
}

// ApplyResetPassToken provides a mock function with given fields: _a0, _a1
func (_m *ResetPassTokenRepository) ApplyResetPassToken(_a0 context.Context, _a1 dto.ApplyResetPassReq) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ApplyResetPassReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateResetPassToken provides a mock function with given fields: _a0, _a1
func (_m *ResetPassTokenRepository) CreateResetPassToken(_a0 context.Context, _a1 model.ResetPassToken) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ResetPassToken) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewResetPassTokenRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewResetPassTokenRepository creates a new instance of ResetPassTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewResetPassTokenRepository(t mockConstructorTestingTNewResetPassTokenRepository) *ResetPassTokenRepository {
	mock := &ResetPassTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
