// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "git.garena.com/sea-labs-id/bootcamp/batch-02/ziad-rahmatullah/assignment-go-rest-api/dto"
	mock "github.com/stretchr/testify/mock"
)

// ResetPasswordUsecase is an autogenerated mock type for the ResetPasswordUsecase type
type ResetPasswordUsecase struct {
	mock.Mock
}

// ApplyPassReset provides a mock function with given fields: _a0, _a1
func (_m *ResetPasswordUsecase) ApplyPassReset(_a0 context.Context, _a1 dto.ApplyResetPassReq) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ApplyResetPassReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestPassReset provides a mock function with given fields: _a0, _a1
func (_m *ResetPasswordUsecase) RequestPassReset(_a0 context.Context, _a1 dto.RequestResetPassReq) (*dto.RequestResetPassRes, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *dto.RequestResetPassRes
	if rf, ok := ret.Get(0).(func(context.Context, dto.RequestResetPassReq) *dto.RequestResetPassRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RequestResetPassRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.RequestResetPassReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewResetPasswordUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewResetPasswordUsecase creates a new instance of ResetPasswordUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewResetPasswordUsecase(t mockConstructorTestingTNewResetPasswordUsecase) *ResetPasswordUsecase {
	mock := &ResetPasswordUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
